export {default as Nav} from './nav'
export {default as Home} from './home'
export {default as About} from './about'
export {default as Skill} from './skill'
export {default as Project} from './project'
export {default as Contact} from './contact'